"""empty message

Revision ID: 95713146f7e0
Revises: f32b36c2148a
Create Date: 2023-05-15 21:32:37.495638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95713146f7e0'
down_revision = 'f32b36c2148a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
